//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateMonitorControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateMonitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StateMonitor()
        {
            this.StateMonitorMetrics = new HashSet<StateMonitorMetric>();
        }
    
        public long stateMonitorId { get; set; }
        public string status { get; set; }
        public string thingType { get; set; }
        public string thingLvl { get; set; }
        public string thingName { get; set; }
        public Nullable<long> thingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateMonitorMetric> StateMonitorMetrics { get; set; }
    }
}
