//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateMonitorControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public long stateId { get; set; }
        public string descState { get; set; }
        public string color { get; set; }
        public string startValue { get; set; }
        public string endValue { get; set; }
        public string message { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<long> stateMonitorMetricId { get; set; }
    
        public virtual StateMonitorMetric StateMonitorMetric { get; set; }
    }
}
