//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateMonitorControl.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STATE_MONITOR_DBEntities : DbContext
    {
        public STATE_MONITOR_DBEntities()
            : base("name=STATE_MONITOR_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StateMonitorMetric> StateMonitorMetrics { get; set; }
        public virtual DbSet<StateMonitor> StateMonitors { get; set; }
        public virtual DbSet<State> States { get; set; }
    }
}
