//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateMonitorControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateMonitorMetric
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StateMonitorMetric()
        {
            this.States = new HashSet<State>();
        }
    
        public long stateMonitorMetricId { get; set; }
        public string descMetric { get; set; }
        public string measuredTag { get; set; }
        public Nullable<long> stateMonitorId { get; set; }
    
        public virtual StateMonitor StateMonitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State> States { get; set; }
    }
}
